apiVersion: v1
kind: Service
metadata:
  name: app-a-service
  namespace: appns-a
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      port: 80          # Port wewnętrzny klastra
      targetPort: 80     # Port, na którym aplikacja nasłuchuje w podzie
      nodePort: 30001    # Port zewnętrzny na węzłach, na którym będzie dostępna usługa
  type: NodePort       # Zmieniamy typ na NodePort, aby dostęp był z zewnątrz
