apiVersion: v1
kind: Service
metadata:
  name: app-b-service
  namespace: appns-b
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 80          # Port wewnętrzny klastra
      targetPort: 80     # Port, na którym aplikacja nasłuchuje w podzie
      nodePort: 30002    # Port zewnętrzny na węzłach, na którym będzie dostępna usługa
  type: NodePort 
